/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitteesSlugRouteImport } from './routes/committees.$slug'
import { Route as CommitteesSlugCountryRouteImport } from './routes/committees.$slug.$country'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesSlugRoute = CommitteesSlugRouteImport.update({
  id: '/committees/$slug',
  path: '/committees/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesSlugCountryRoute = CommitteesSlugCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => CommitteesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committees/$slug': typeof CommitteesSlugRouteWithChildren
  '/committees/$slug/$country': typeof CommitteesSlugCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committees/$slug': typeof CommitteesSlugRouteWithChildren
  '/committees/$slug/$country': typeof CommitteesSlugCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committees/$slug': typeof CommitteesSlugRouteWithChildren
  '/committees/$slug/$country': typeof CommitteesSlugCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/committees/$slug' | '/committees/$slug/$country'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/committees/$slug' | '/committees/$slug/$country'
  id: '__root__' | '/' | '/committees/$slug' | '/committees/$slug/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteesSlugRoute: typeof CommitteesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees/$slug': {
      id: '/committees/$slug'
      path: '/committees/$slug'
      fullPath: '/committees/$slug'
      preLoaderRoute: typeof CommitteesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees/$slug/$country': {
      id: '/committees/$slug/$country'
      path: '/$country'
      fullPath: '/committees/$slug/$country'
      preLoaderRoute: typeof CommitteesSlugCountryRouteImport
      parentRoute: typeof CommitteesSlugRoute
    }
  }
}

interface CommitteesSlugRouteChildren {
  CommitteesSlugCountryRoute: typeof CommitteesSlugCountryRoute
}

const CommitteesSlugRouteChildren: CommitteesSlugRouteChildren = {
  CommitteesSlugCountryRoute: CommitteesSlugCountryRoute,
}

const CommitteesSlugRouteWithChildren = CommitteesSlugRoute._addFileChildren(
  CommitteesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteesSlugRoute: CommitteesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
